#  ----------------------------------------------------------------------------
# This action / workflow:
# - greets first time issuer
# - greets first time PR
#
# Using: https://github.com/marketplace/actions/first-interaction
#  ----------------------------------------------------------------------------

name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you very much for your first issue to this project. It is much appreciated.'
        pr-message: 'Thank you very much for your first pull request to this project. It is much appreciated.'
